version: '3.9'
services:
  nginx:
    build: ./nginx
    ports:
      - 80:80

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_DATABASE: spindex
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: db_user
      PMA_PASSWORD: db_user_pass
      # PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80

  web:
    depends_on:
      - db
    environment:
      - DATABASE=red
    build: .
    ports:
     - 5000:5000
    command: node start
    volumes:
     - .:/code


volumes:
  dbdata:

networks:
  db-net:

    